### ISSUE TITLE
cdh 6.x 支持

### ISSUE THREAD

**Issue by xuanbo** [AlionSSS/CDH-Install-Manual#1]
是否考虑 cdh 6.x 支持 :)

**Comment by AlionSSS** [comment]
- cdh 6.x 的安装手册，我个人暂时没空弄了。
- 不过互联网上目前已经有很多教程了。看看5.x的手册，再参考下网上的资料，应该很容易就会了 :)

**Comment by AlionSSS** [comment]
> 是否考虑 cdh 6.x 支持 :)

- cdh 6.x 的安装手册，我个人暂时没空弄了。
- 不过互联网上目前已经有很多教程了。看看5.x的手册，再参考下网上的资料，应该很容易就会了 :)

**Comment by AlionSSS** [comment]
> 是否考虑 cdh 6.x 支持 :)

- cdh 6.x 的安装手册，我个人暂时没空弄了。
- 不过互联网上目前已经有很多教程了。看看5.x的手册，再参考下网上的资料，应该很容易就会了 :yum:
